
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (1,'Movistar Team','Eusebio Unzue',8,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (2,'INEOS Grenadiers','Dave Brailsford',18,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (3,'AG2R Citroën Team','Vincent Lavenu',3,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (5,'EF Education - EasyPost','Jonathan Vaughters',6,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (6,'Groupama - FDJ','Marc Madiot',3,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (9,'Lotto Soudal','John Lelangue',4,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (10,'Quick Step-Alpha Vinyl','Patrick Lefevere',4,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (11,'Trek - Segafredo','Luca Guercilena',6,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (12,'Astana Qazaqstan Team','Alexandre Vinokurov',13,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (13,'Bahrain Victorious','Milan Erzen',106,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (14,'Team Jumbo - Visma','Richard Plugge',5,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (15,'Team DSM','Iwan Spekenbrink',5,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (16,'UAE Team Emirates','Jose Antonio Fernandez',105,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (20,'Team BikeExchange Jayco','Brent Copeland',20,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (24,'Team Arkéa - Samsic','Emmanuel Hubert',3,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (25,'TotalEnergies','Jean-René Bernaudeau',3,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (33,'BORA - hansgrohe','Ralph Denk',7,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (34,'Cofidis','Cédric Vasseur',3,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (35,'Caja Rural - Seguros RGA','Juan Manuel Hernandez',8,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (37,'Alpecin-Fenix','Philip Roodhooft',4,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (38,'Atum General / Tavira / AP Maria Nova Hotel','Vidal Fitas',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (40,'Team Vorarlberg','Thomas Kafler',37,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (42,'Israel - Premier Tech','Kjell Carlström',70,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (43,'Drone Hopper - Androni Giocattoli','Gianni Savio',2,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (44,'B&B HOTELS p/b KTM','Jérôme Pineau',3,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (45,'Amore e Vita - KIBAG - DFT - Obor','Cristian Fanini',78,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (50,'Adria Mobil','Bodgan Fink',28,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (58,'Elkov - Kasper','Vladimir Vavra',33,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (59,'Go Sport - Roubaix Lille Métropole','Jean-Charles Canonne',3,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (65,'Intermarché - Wanty - Gobert Matériaux','Jean-François Bourlart',4,1);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (68,'St Michel - Auber 93','Stéphane Javalet',3,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (69,'Sport Vlaanderen - Baloise','Christophe Sercu',4,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (70,'Equipo Kern Pharma','Juan Josè Oroz',8,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (71,'Leopard Pro Cycling','Markus Zingen',19,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (81,'Bardiani CSF Faizanè','Roberto Reverberi',2,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (86,'Riwal Cycling Team','Steffen Juel Kromann',10,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (87,'Bingoal - Pauwels Sauces - WB','Christophe Brandt',4,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (90,'Bingoal Pauwels Sauces WB Development Team','Jean-Denis Vandenbroucke',4,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (92,'Burgos - BH','Julio Andres Izquierdo',8,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (95,'Team UKYO','Tadahiko Kowebare',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (96,'Vino SKO Team','Venera Govrolova',13,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (99,'Uno-X Pro Cycling Team','Jens Haugland',35,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (100,'Euskaltel - Euskadi','Jesus Ezkurdia',8,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (101,'Gazprom - RusVelo','Renat Khamidulin',15,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (102,'EOLO - Kometa Cycling Team','Francisco Contador',2,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (104,'Minsk Cycling Club','Aliaksandr Kuchynski',43,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (105,'Glassdrive / Q8 / Anicolor','Rúben Pereira',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (106,'HRE Mazowsze Serce Polski','Darius Benezek',30,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (109,'Rádio Popular - Boavista','Jose Santos',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (110,'Tarteletto - Isorex','Peter Bauwens',4,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (111,'WiV SunGod','Tim Alvorson',18,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (112,'Hrinkow Advarics Cycleang','Alexander Hraukaw',37,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (114,'Tirol KTM Cycling Team','Thomas Popp',37,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (115,'Team Felbermayr Simplon Wels','Christoph Palmer',37,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (117,'W52 / FC Porto','Adriano Sousa',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (123,'Team Novo Nordisk','Vassili Davidenko',6,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (132,'D''Amico - UM Tools','Ivan De Paolo',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (135,'Hagens Berman Axeon','Addy Legend',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (140,'Metec - Solarwatt p/b Mantel','Gianni Van Haafen',5,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (141,'Human Powered Health','Jacob Erker',6,2);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (146,'ABLOC CT','Paul Tabak',5,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (147,'Team ColoQuick','Brian Taperson',10,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (149,'Mg.K Vis Colors for Peace VPM','Maurizio Frizzo',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (150,'Team Coop','Jan Erik Fjotland',35,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (152,'Rad-Net Rose Team','Ulrich Möller',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (153,'Team Lotto - Kern Haus','Florian Manrole',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (158,'BEAT Cycling','Geert Broekhuizen',5,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (159,'Evopro Racing','Maria Fox',31,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (160,'Biesse - Carrera','Marco Milesi',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (161,'BHS - PL Beton Bornholm','Christian Juul Andreasen',10,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (162,'Voster ATS Team','Mariusz Witecki',30,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (163,'Geofco-Doltcini Materiel-Velo.com','Sébastien Fontaine',4,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (164,'Elevate p/b Home Solution-Soenens','Kevin Hulsmans',4,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (165,'MEIYO CCN Pro Cycling','Kai Wing Herman Tam',84,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (166,'Minerva Cycling Team','Preben Van Hecke',4,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (167,'Allinq Continental Cyclingteam','Kelvin Dekker',5,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (168,'Nice Métropole Côte d''Azur','Jérome Poulidori',3,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (169,'Team U Nantes - Atlantique','Anthony Ravard',3,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (170,'Gallina Ecotek Lucchini','Mario Cesare Turchetti',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (171,'Efapel Cycling','José Bento Azevedo',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (172,'Santic - Wibatech Continental Team','Wieslaw Ciasnocha',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (173,'Manuela Fundación Continental','Jose Vicente Bonillo Hervas',8,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (174,'Astana Qazaqstan Development Team','Alexandre Vinokurov',13,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (175,'Premier Tech U23 Cycling Project','Flavien Dassonville',22,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (176,'Team Corratec','Serge Parsani',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (177,'Ferei-CCN Metalac','Radisa Cubric',50,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (178,'Vozrozhdenie','Mikhail Rostovtsev',15,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (179,'Cycling Team Kranj','Matjaz Zevnik',28,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (180,'Motala AIF Serneke Allebike','Lars Wahlqvist',32,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (181,'Victoire Hiroshima','Takushi Nakayama',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (183,'Kaunas Cycling Team','Donatas Sertvytis',14,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (184,'Ferei Mongolia Development Team',NULL,83,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (185,'MitoQ - NZ Cycling Project','James Canny',34,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (186,'Agrupacion Virgen de Fatima - San Juan Biker Motos','Carlos Nicolas Gomez',46,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (187,'Municipalidad de Rawson Somos Todos','Elsa Susana Fernandez',46,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (188,'Chimbas Te Quiero','Emiliano Fernandez',46,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (189,'Electro 3 - Gremios por el Deporte','Guillermo Tula Aguiar',46,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (190,'Saitel',NULL,94,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (191,'BAI - Sicasal - Petro de Luanda','Carlos De Araujo',77,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (192,'The Hurricane & Thunder Cycling Team','Yeerjianati Baolati',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (193,'Henan Bodywrap Cycling Team','Shanshan Ma',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (194,'Tashkent City Professional Cycling Team','Ruslan Useynov',57,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (195,'MENtoRISE Elite Team CFX','Ovidu Burghelea',104,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (196,'Grant Thornton Bike Zone','Sebastien Duclos',82,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (197,'Toronto Hustle','Benjamin Baker',22,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (198,'Arvich Shargh Omidnia','Abdolmotalleb Karimi',78,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (200,'7 Eleven Cliqq - Air21 by Roadbike Philippines','Ric Rodriguez',88,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (202,'Development Team DSM','Roy Curvers',5,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (203,'Team Qhubeka','Douglas Ryder',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (210,'Equipe continentale Groupama-FDJ','Jens Blatter',3,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (211,'Israel Cycling Academy','Chen Tal',70,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (213,'Bahrain Cycling Academy','Kolja Koracak',106,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (214,'Jumbo-Visma Development Team','Richard Plugge',5,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (215,'Team Sapura Cycling','Sayuti Zahit',49,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (216,'Terengganu Polygon Cycling Team','Jeremy Hunt',49,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (217,'Team Medellin - EPM','Jose Julian Velazquez de la Cuesta',11,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (218,'St George Continental Cycling Team','Brett Dutton',20,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (219,'Team BridgeLane','Tom Petty',20,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (221,'Team Colpack Ballan','Antonio Bevilacqua',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (222,'Bike Aid','Jacob Buijk',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (223,'Team Illuminate','Chris Johnson',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (224,'ARA Pro Racing Sunshine Coast','Ben Kersten',20,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (225,'Ribble Weldtite Pro Cycling','Colin Sturgess',18,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (226,'Swiss Racing Academy','Sylvain Blanquefort',17,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (227,'Bolton Equities Black Spoke Pro Cycling','Scott Guyton',34,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (230,'Cycling Team Friuli ASD','Renzo Boscolo',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (231,'Maloja Pushbikers','Rupert Hödlmoser',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (232,'ABTF - Feirense','Joaquim Andrade',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (233,'Elevate - Webiplex Pro Cycling','Pablo Abrahams',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (235,'Team Novo Nordisk Development','Sergey Lagutin',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (237,'Aisan Racing Team','Kenji Nakane',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (238,'Start Cycling Team','Mauricio Frazer',45,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (239,'Equipo Continental Municipalidad de Pocito','Rubén Eleazar Ramos',46,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (241,'Team Bridgestone Cycling','Junichi Shibuya',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (242,'Hengxiang Cycling Team','Guyu Li',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (243,'Utsunomiya Blitzen','Yusuke Shimizu',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (244,'Canel''s - ZeroUno','Juan José Monsivais Garcia',23,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (246,'KFC Cycling Team','Mohammad Aliza Gibran',85,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (247,'Kinan Cycling Team','Tetsuya Ishida',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (248,'KSPO Professional','Sandeul Kang',79,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (250,'Ljubljana Gusto Santic','Luka Zele',28,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (256,'A.R. Monex Pro Cycling Team','Franco Lampugnani',65,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (259,'Tavfer-Mortágua-Ovos Matinados','Leonor Silva',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (261,'Giant Cycling Team','Guo Qiang Song',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (267,'Saris Rouvy Sauerland Team','Wolfgang Oschwald',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (269,'Thailand Continental Cycling Team','Wisut Kasiyaphat',82,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (270,'Team Dauner - Akkon','Marion Zimmerman',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (275,'Team Novak','Tamás Csicsáky',104,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (278,'Tianyoude Hotel Cycling Team','Yilin Tao',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (279,'Uijeongbu Cycling Team','Hanjong Jeong',79,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (295,'Seoul Cycling Team','Bonjae Ku',79,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (296,'Sindicato Empleados Públicos of San Juan','Sergio Fabian Gili',46,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (297,'MULA','Satria Agung Purwanto',85,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (299,'Aviludo - Louletano - Loulé Concelho','Jorge Piedade',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (303,'Lokosphinx','Denis Smyslov',15,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (305,'Korail Cycling Team','Eunchul Do',79,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (309,'Gapyeong Cycling Team','Chanil Oh',79,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (347,'Benediction Ignite XL','Benoit Munyankindi',42,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (349,'Pio Rico Cycling Team','Luis Cesar Rodriguez Escaray',92,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (356,'CCN Factory Racing','Anatoli Sizko',43,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (359,'Giotti Victoria Savini Due','Gabriele Di Francesco',104,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (360,'Go For Gold Philippines','Ednalyn Calitis Hualda',88,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (361,'Foolad Mobarakeh Sepahan','Mohammad Bagheri Gavarti',78,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (362,'Carnovali - Rime','Daniele Calosso',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (363,'Roojai.com Cycling Team','Peter Pouly',85,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (365,'L.A. Aluminios / L.A. Sport','Luis Almeida',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (366,'Meridiana Kamen Team','Antonio Giallorenzo',44,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (368,'ProTouch','Tony Harding',36,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (369,'P&S Benotti','Lars Wackernagel',7,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (372,'SwiftCarbon Pro Cycling Brasil','Marcelo Donnabella',56,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (409,'VolkerWessels Cycling Team','Allard Engels',5,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (410,'WSA KTM Graz p/b Leomo','Christoph Resl',37,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (411,'Salcano Sakarya BB Team','Aziz Sirnac',71,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (412,'Sidi Ali - Unlock Team','Ait Oufqir Hamza',26,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (415,'ATT Investments','Petr Kaltofen',33,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (416,'SKOL Adrien Niyonshuti Cycling Academy','Adrien Niyonshuti',42,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (418,'Spor Toto Cycling Team','Muhammed Atalay',71,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (419,'Movistar - Best PC','Anderson Padilla',94,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (421,'Azad University Team','Naser Houshyar',78,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (423,'Li Ning Star Cycling Team','Zhe Sun',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (424,'Pardus Cycling Team','Yongyan Sheng',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (426,'Uno-X Dare Development Team','Max Emil Boholm Kørner',35,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (427,'Lviv Continental Cycling Team','Oleksandr Seliverstov',38,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (443,'Saint Piran','Richard Pascoe',18,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (444,'Global6 Cycling','James Mitri',34,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (445,'Colnago CM Team','Carlos Alejandro Restrepo',11,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (446,'China Glory Continental Cycling Team','Amaël Moinard',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (447,'China Huajian Cycling Team','Pin Lv',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (448,'Panamá es Cultura y Valores','Juan Pablo Villegas',102,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (449,'Iraq Cycling Project','Tariq Abdulrahman',132,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (450,'Dukla Banska Bystrica','Martin Fraňo',27,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (311,'Ningxia Sports Lottery Cycling Team','Feng Jun',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (313,'LX Cycling Team','Sunjae Jang',79,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (314,'Massi Vivo - Conecta','Luis Manuel Meaurio',110,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (315,'Nasu Blasen','Atsuhito Wakasugi',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (317,'Tufo - Pardus Prostejov','Michal Mrácek',33,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (318,'AC Sparta Praha','Zdenek Rubas',33,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (320,'Shimano Racing Team','Hisafumi Imanishi',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (325,'Matrix Powertag','Masahiro Yasuhara',21,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (326,'Pauwels Sauzen - Bingoal','Geert Vanhoof',4,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (327,'Baloise - Trek Lions','Sven Nys',4,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (328,'Kuwait Pro Cycling','Fahad Alshammari',107,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (332,'Geumsan Insam Cello','Heedong Choi',79,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (333,'HKSI Pro Cycling Team','King Wai Cheung',80,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (335,'Beltrami TSA Tre Colli','Roberto Miodini',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (336,'China Continental Team of Gansu Bank','Pengda Jiao',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (377,'Taiyuan Miogee Cycling Team','Peng Yang',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (378,'Team Skyline','Michael Tacci',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (379,'Kelly / Simoldes / UDO','Manuel Correia',29,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (380,'Wildlife Generation Pro Cycling','Danny Van Haute',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (381,'Shenzhen Xidesheng Cycling Team','Chao Yin',25,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (382,'XSpeed United Continental','Ricky Lee',22,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (385,'Java Kiwi Atlántico','Enrique Salgueiro Alonso',45,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (389,'Cambodia Cycling Academy','Patrick Aurignac',112,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (390,'Nero Continental','Luke Manion',20,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (391,'Equipo Continental San Luis','Enzo Josue Moyano',46,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (393,'EuroCyclingTrips - CMI Pro Cycling Team','Dirk Van Hove',114,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (395,'General Store - Essegibi - F.lli Curia','Giorgio Furlan',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (398,'Work Service Vitalcare Vega','Demetrio Iommi',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (404,'Almaty Cycling Team','Maxat Ayazbayev',13,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (405,'Team Ampler - Tartu2024','Jaan Kirsipuu',12,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (428,'Zalf Euromobil Désirée Fior','Ilario Contessa',2,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (429,'Eurocar Grawe Ukraine','Sergiy Chmyruk',38,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (430,'Cycling Academy Trenčín','Miroslav Gavenda',27,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (431,'Electro Hiper Europa - Caldas','Rafael Casero',11,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (434,'Restaurant Suri Carl Ras','Nicolaj Bo Larsen',10,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (435,'EF Education-NIPPO Development Team','Marcello Albasini',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (436,'Union Raiffeisen Radteam Tirol','Gregor Pavlic',37,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (437,'SNC Cycling Team','Teng Soon Sik',49,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (438,'BelAz','Vasil Kiriyenka',43,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (439,'Yoeleo Test Team p/b 4Mind','Mark Cumberbatch',22,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (440,'L39ion of Los Angeles','Michael Roecklein',6,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (441,'Trinity Racing','Andrew McQuaid',18,3);
INSERT INTO team(id,team_name,general_manager,country_id,id_division) VALUES (442,'Alpecin-Fenix Development Team','Kris Wouters',4,3);
